# Generated by Django 5.2.7 on 2026-08-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quality_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
