# Generated by Django 5.2.7 on 2026-08-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_quality_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchproduct',
            name='is_active',
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
