# Generated by Django 5.2.7 on 2026-08-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_branchproduct_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
