# Generated by Django 5.2.7 on 2026-08-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='budget_committed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
