# Generated by Django 5.2.7 on 2026-08-24 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0001_initial'),
        ('purchasing', '0002_purchaseorder_budget_committed_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('purchase_type', models.CharField(blank=True, help_text='Vacío: aplica a todos los tipos de compra.', max_length=50, null=True)),
                ('amount_from', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_to', models.DecimalField(blank=True, decimal_places=2, help_text='Vacío: sin tope superior.', max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('legal_entity', models.ForeignKey(blank=True, help_text='Vacío: aplica a todas las razones sociales.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='organizations.legalentity')),
                ('required_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_rules', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Approval Rule',
                'verbose_name_plural': 'Approval Rules',
                'db_table': 'approval_rules',
                'ordering': ['amount_from'],
                'indexes': [models.Index(fields=['legal_entity'], name='idx_approval_rule_entity'), models.Index(fields=['is_active'], name='idx_approval_rule_active')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_from__gte', 0)), name='chk_approval_rule_from_non_negative')],
            },
        ),
    ]
