# Generated by Django 5.2.7 on 2026-08-24 14:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('organizations', '0001_initial'),
        ('products', '0003_remove_branchproduct_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('block', models.CharField(choices=[('OPERACION_INGRESO', 'Operación - Ingreso'), ('OPERACION_EGRESO', 'Operación - Egreso'), ('INVERSION_EGRESO', 'Inversión - Egreso'), ('FINANCIAMIENTO_INGRESO', 'Financiamiento - Ingreso'), ('FINANCIAMIENTO_EGRESO', 'Financiamiento - Egreso')], max_length=40)),
                ('sign', models.SmallIntegerField(choices=[(1, 'Entrada de caja'), (-1, 'Salida de caja')], default=-1)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Budget Category',
                'verbose_name_plural': 'Budget Categories',
                'db_table': 'budget_categories',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='budget',
            name='uq_budget_scope',
        ),
        migrations.AddField(
            model_name='budget',
            name='committed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Desglose opcional por categoría de producto dentro de la línea.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='products.productcategory'),
        ),
        migrations.AddIndex(
            model_name='budgetcategory',
            index=models.Index(fields=['block'], name='idx_budget_category_block'),
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_category',
            field=models.ForeignKey(blank=True, help_text='Línea del presupuesto de caja a la que pertenece este monto.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='finance.budgetcategory'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('committed_amount__gte', 0)), name='chk_budget_committed_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('legal_entity', 'branch', 'cost_center', 'budget_category', 'category', 'period_year', 'period_month'), name='uq_budget_scope'),
        ),
    ]
