# Generated by Django 5.2.7 on 2026-08-24 14:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_budgetcategory_remove_budget_uq_budget_scope_and_more'),
        ('organizations', '0001_initial'),
        ('products', '0003_remove_branchproduct_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoiceItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('budget_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_items', to='finance.budgetcategory')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoice_items', to='products.productcategory')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoice_items', to='organizations.costcenter')),
                ('product', models.ForeignKey(blank=True, help_text='Vacío para gastos sin producto de catálogo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_items', to='products.product')),
                ('supplier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.supplierinvoice')),
            ],
            options={
                'verbose_name': 'Supplier Invoice Item',
                'verbose_name_plural': 'Supplier Invoice Items',
                'db_table': 'supplier_invoice_items',
                'indexes': [models.Index(fields=['supplier_invoice'], name='idx_invoice_item_invoice'), models.Index(fields=['cost_center'], name='idx_invoice_item_cost_center')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='chk_invoice_item_quantity_positive')],
            },
        ),
    ]
