# Generated by Django 5.2.7 on 2026-08-12 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplier_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='image',
        ),
    ]
