# Generated by Django 5.2.7 on 2026-08-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_remove_supplier_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
