# Generated by Django 5.2.7 on 2026-08-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_alter_supplier_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='payment_terms_days',
            field=models.PositiveIntegerField(blank=True, help_text='Días desde la emisión de la factura hasta su vencimiento.', null=True),
        ),
    ]
