# Generated by Django 5.2.7 on 2026-08-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorystock',
            name='max_level',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='min_level',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
    ]
