# Generated by Django 5.2.7 on 2026-08-24 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('organizations', '0002_legalentityalias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Financier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('financier_type', models.CharField(choices=[('FONASA', 'FONASA'), ('ISAPRE', 'Isapre'), ('CONVENIO', 'Convenio institucional'), ('PARTICULAR', 'Particular'), ('OTRO', 'Otro')], default='OTRO', max_length=40)),
                ('generates_receivable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Financier',
                'verbose_name_plural': 'Financiers',
                'db_table': 'financiers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['financier_type'], name='idx_financier_type')],
            },
        ),
        migrations.CreateModel(
            name='RevenueImportBatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_imported', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('unmapped_providers', models.JSONField(blank=True, default=list)),
                ('unmapped_financiers', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PREVISUALIZADO', 'Previsualizado'), ('IMPORTADO', 'Importado'), ('FALLIDO', 'Fallido')], default='PREVISUALIZADO', max_length=40)),
                ('notes', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_batches', to='documents.document')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revenue Import Batch',
                'verbose_name_plural': 'Revenue Import Batches',
                'db_table': 'revenue_import_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancierAlias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('raw_name', models.CharField(max_length=180, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('financier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='revenue.financier')),
            ],
            options={
                'verbose_name': 'Financier Alias',
                'verbose_name_plural': 'Financier Aliases',
                'db_table': 'financier_aliases',
                'indexes': [models.Index(fields=['raw_name'], name='idx_financier_alias_raw')],
            },
        ),
        migrations.CreateModel(
            name='RevenueEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('service_date', models.DateField()),
                ('appointment_ref', models.CharField(blank=True, max_length=80, null=True)),
                ('procedure_code', models.CharField(blank=True, max_length=80, null=True)),
                ('procedure_name', models.CharField(blank=True, max_length=255, null=True)),
                ('modality', models.CharField(blank=True, max_length=80, null=True)),
                ('room', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(blank=True, max_length=80, null=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_entries', to='organizations.branch')),
                ('financier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_entries', to='revenue.financier')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_entries', to='organizations.legalentity')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='revenue.revenueimportbatch')),
            ],
            options={
                'verbose_name': 'Revenue Entry',
                'verbose_name_plural': 'Revenue Entries',
                'db_table': 'revenue_entries',
                'ordering': ['-service_date'],
                'indexes': [models.Index(fields=['legal_entity', 'service_date'], name='idx_revenue_entity_date'), models.Index(fields=['financier', 'service_date'], name='idx_revenue_financier_date'), models.Index(fields=['branch'], name='idx_revenue_branch')],
                'constraints': [models.UniqueConstraint(fields=('import_batch', 'appointment_ref', 'procedure_code'), name='uq_revenue_entry_source')],
            },
        ),
    ]
