# Generated by Django 5.2.7 on 2026-08-24 14:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('organizations', '0002_legalentityalias'),
        ('revenue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountReceivable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('period_year', models.IntegerField()),
                ('period_month', models.IntegerField()),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('billed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Cobro parcial'), ('COBRADA', 'Cobrada'), ('CASTIGADA', 'Castigada')], default='PENDIENTE', max_length=40)),
                ('notes', models.TextField(blank=True, null=True)),
                ('financier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='revenue.financier')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='organizations.legalentity')),
            ],
            options={
                'verbose_name': 'Account Receivable',
                'verbose_name_plural': 'Accounts Receivable',
                'db_table': 'accounts_receivable',
                'ordering': ['-period_year', '-period_month'],
            },
        ),
        migrations.CreateModel(
            name='AccountReceivableItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('account_receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='revenue.accountreceivable')),
                ('revenue_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivable_items', to='revenue.revenueentry')),
            ],
            options={
                'verbose_name': 'Account Receivable Item',
                'verbose_name_plural': 'Account Receivable Items',
                'db_table': 'accounts_receivable_items',
            },
        ),
        migrations.CreateModel(
            name='CashCollection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('collection_date', models.DateField()),
                ('particular_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('copay_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('withdrawal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('check_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('branch', models.ForeignKey(blank=True, help_text='Vacío cuando el informe consolida varias sucursales.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_collections', to='organizations.branch')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_collections', to='organizations.legalentity')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_collections', to='documents.document')),
            ],
            options={
                'verbose_name': 'Cash Collection',
                'verbose_name_plural': 'Cash Collections',
                'db_table': 'cash_collections',
                'ordering': ['-collection_date'],
            },
        ),
        migrations.AddIndex(
            model_name='accountreceivable',
            index=models.Index(fields=['legal_entity', 'financier'], name='idx_receivable_entity_fin'),
        ),
        migrations.AddIndex(
            model_name='accountreceivable',
            index=models.Index(fields=['status'], name='idx_receivable_status'),
        ),
        migrations.AddConstraint(
            model_name='accountreceivable',
            constraint=models.CheckConstraint(condition=models.Q(('period_month__gte', 1), ('period_month__lte', 12)), name='chk_receivable_month'),
        ),
        migrations.AddConstraint(
            model_name='accountreceivable',
            constraint=models.UniqueConstraint(fields=('legal_entity', 'financier', 'period_year', 'period_month'), name='uq_receivable_period'),
        ),
        migrations.AddConstraint(
            model_name='accountreceivableitem',
            constraint=models.UniqueConstraint(fields=('account_receivable', 'revenue_entry'), name='uq_receivable_item'),
        ),
        migrations.AddIndex(
            model_name='cashcollection',
            index=models.Index(fields=['legal_entity', 'collection_date'], name='idx_collection_entity_date'),
        ),
        migrations.AddConstraint(
            model_name='cashcollection',
            constraint=models.UniqueConstraint(fields=('legal_entity', 'branch', 'collection_date'), name='uq_cash_collection_day'),
        ),
    ]
