# Generated by Django 5.2.7 on 2026-08-24 14:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntityAlias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('alias_type', models.CharField(choices=[('CODIGO_PRESTADOR', 'Código de prestador'), ('NOMBRE', 'Nombre alternativo')], default='CODIGO_PRESTADOR', max_length=40)),
                ('value', models.CharField(max_length=180, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='organizations.legalentity')),
            ],
            options={
                'verbose_name': 'Legal Entity Alias',
                'verbose_name_plural': 'Legal Entity Aliases',
                'db_table': 'legal_entity_aliases',
                'indexes': [models.Index(fields=['value'], name='idx_le_alias_value')],
            },
        ),
    ]
